# Generated by Django 4.1 on 2022-08-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField(max_length=100)),
                ('card_text', models.CharField(max_length=100)),
                ('card_img', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
